### ISSUE TITLE
Prevent Sale Amount Entered From Being Greater Than Shares Owned

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#113]
![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/46d13767-d65f-4532-937f-4cf786c623ea)

**Comment by shahzad713** [comment]
@pwdel   So could we use The external Library for this Ui as well ?

**Comment by pwdel** [comment]
Yes we could.

So I would like a holistic look at what external libraries we introduce into the code to try to avoid introducing too many and creating a base that is harder to maintain.

That being said, some core functionality could be probably very much improved with a refactor with certain types of libraries.

Here is where I have put a discussion board for different kinds of library ideas for all sorts of purposes across the entire frontend app.

https://github.com/orgs/openpredictionmarkets/projects/2

I would say, if you have a good idea, perhaps start a ticket on that project exactly for the library you would suggest. I aim to put a bunch more suggested libraries in there to evaluate soon too.

What do you think?

**Comment by pwdel** [comment]
Fixed in v0.0.3, currently on branch "profilepage"
