### ISSUE TITLE
Error Handling if No Markets

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#125]
If there are no markets created yet, the front end doesn't know what to do.

**Comment by pwdel** [comment]
![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/d8f9db22-9210-4882-9412-07f45e416689)

**Comment by markokovac16** [comment]
Conditional rendering sorts out these issues

I like to implement a loader until the data is pulled and rendered in order to ensure these errors don't happen

If there's no data, render a relevant message

**Comment by pwdel** [comment]
For some reason, the PR as I have created it thus far breaks, "Create.jsx," such that it enters in an invalid date.

**Comment by pwdel** [comment]
@markokovac16 would you happen to be able to look at this?

**Comment by pwdel** [comment]
Awesome, thanks!

**Comment by markokovac16** [comment]
Fixed here https://github.com/openpredictionmarkets/socialpredict/commit/2fb05e6209a1ea65d197e97d07ae63c756838597
