### ISSUE TITLE
Improve Setup Readme File

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#130]
Task Outline:

1. We should specify a supported Docker / docker-compose version according to what we had found back in March. I don't remember what those versions were but I believe we talked about it here on upwork. 

2. We should specify Ubunutu or MacOS as the supported machines. 

3. We should eliminate the ability to Seed bets, only seed users and Markets, because the way bets work has totally changed where if a user buys a NO, it force sells YES and vice versa. 

4. I'm not sure why we need to copy the .env file,... or if that's needed, that might be BS. "Create a copy of the .[env.dev](http://env.dev/) with this command cp .[env.dev](http://env.dev/) .env." ... we can probably delete that? 

5. API access I think is at :8089 ... not sure why it says 8086, if that's old...? Access the API at localhost:8086 ... we should probably unify that to a single port. 

6. Troubleshooting ... we shouldn't ask people to go back to v0.0.2 anymore since that version is so old at this point, it's irrelevant. 

7. Shutting down ... the shut down code is now ./compose-dev-down not the direct docker-compose command.

**Comment by pwdel** [comment]
Comments from Marko:



![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/3743dd72-72f2-4bfd-8c10-85e81ed3830c)




![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/22d19448-5b3d-447c-9368-b65d973dd2ef)

**Comment by pwdel** [comment]
Re:



![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/e2fe6cac-67c0-4ef8-804e-26e1d5987909)



Yes, this is being covered in https://github.com/orgs/openpredictionmarkets/projects/1/views/1?pane=issue&itemId=62418955

**Comment by pwdel** [comment]
Hey, I tried to document everything here.

https://github.com/orgs/openpredictionmarkets/projects/1/views/1?pane=issue&itemId=63031816

Do you want to create the updated LOCAL https://github.com/openpredictionmarkets/socialpredict/blob/main/README/LOCAL_SETUP.md and then link to it from the main readme?

**Comment by pwdel** [comment]
If you pull from master again, don't think you need to rebuild the image, then some problems with owning double shares (e.g. both NO and YES) shares simultaneously have been fixed...however there is a problem with the seeded markets and not being able to bet on them initially. I wonder if we should just get rid of seeding markets as well.

**Comment by markokovac16** [comment]
On it! :)

**Comment by markokovac16** [comment]
Done!

https://github.com/openpredictionmarkets/socialpredict/commit/81a4de9bb735b83b5d1c5ffdc0f66e42271981ab

**Comment by pwdel** [comment]
Made some additional changes and removed the capability to seed bets since that doesn't add any value any more. Previously I had been using seeded bets just to get a quick idea of what the visualization would look like.

https://github.com/openpredictionmarkets/socialpredict/pull/132/files
