### ISSUE TITLE
Sidebar Should Include Icons for Mobile Compatibility

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#142]

**Comment by markokovac16** [comment]
We need to decide which buttons we want there with their respective icons and the rest of the options should go in a header of sorts with a profile pic which on click turns into a sidebar with the rest of the options

**Comment by pwdel** [comment]
Do you have a screenshot example of this?

When you say, "respective icons," are you referring to like, how Twitter has icons representing the different menu items?

<img width="108" alt="image" src="https://github.com/openpredictionmarkets/socialpredict/assets/13304149/88f61b19-bad3-47a4-bd41-731adfd1ad62">

Profile pic...so, I wanted to build this with no images for v0.0.3 to start off with, because if we use images, that implies that we have to upload them somewhere, build some kind of interface to upload them etc.  If we ask users who are deploying this to allow images, that means their server (which could be something small like a Raspberry Pi) will start to get filled with images. I wanted to approach images as an opt-in, along with a plugin to S3 that people could use, so hosting images is muh more reliable. 

However we do have custom emojis, so that could suffice as a pic for now, for v0.0.3, etc.

**Comment by markokovac16** [comment]
We can always use an icon library like https://www.flaticon.com/free-icons/react for example

As for the profile pic, for starters I'd just put a generic blank profile pic to indicate it's a clickable area

**Comment by pwdel** [comment]
OK, I started with an example just to see how that would work.

Crappy example, bad sizing...made the SVG myself, just wanted to set a pattern.

https://github.com/openpredictionmarkets/socialpredict/pull/148

You will likely need to rebuild the backend image if you haven't pulled master recently.

So just so I understand, you are suggesting icons because if we compress into a, "bottom of the page," on mobile version, we're going to need very small components to get it to all fit, right?

I could see using one consistent style on flaticons as an example, and then we quickly create our own set of SVG's as examples to get something going, make sure they have the right size, and then push to this branch.

![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/2516bd2b-e440-4986-b3e5-32d34063b7b7)

Go ahead and add anything you would like if you have time, otherwise I will try to blaze through it when I have time in the next few days. Let me know if you want to work on this, we can create a patrick and marko branch separately which pulls into this one, otherwise I'll just use this branch.

Thanks, great idea.

**Comment by pwdel** [comment]
OK, roughly, I'm going to try to stick with, "lineal" style by Freepic

https://www.flaticon.com/search?style_id=1&author_id=1&word=user&type=standard

Looks like this:

![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/8b0eadba-2a07-4446-bc90-eb30d9af7801)

**Comment by pwdel** [comment]
OK, updated.

However I can't seem to set the right margin to the right of the components in the sidebar.

![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/f3b3f7f1-6f23-40d2-872e-ab5041e89d8a)

If I change the mr-2 to mr-4 or mr-6 it doesn't change the spacing.

```
                                        <Link to="/profile" className="sidebar-link flex items-center">
                                            <ProfileSVG className="mr-2" />
                                            Profile
                                        </Link>
```

**Comment by pwdel** [comment]
I have the icons working across all menus so I'm going to merge this and then start a new issue specifically for mobile compatibility since that's a more complicated issue.

https://github.com/orgs/openpredictionmarkets/projects/1/views/1?pane=issue&itemId=65192982
