### ISSUE TITLE
Sidebar Should Change to Bottom Bar in Mobile Mode

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#150]

**Comment by pwdel** [comment]
Creating as a continuation of https://github.com/orgs/openpredictionmarkets/projects/1/views/1?pane=issue&itemId=64144893

**Comment by pwdel** [comment]
Some tutorials I could breeze through to get an idea of how this *should* be architected.

* https://v1.tailwindcss.com/course/making-the-navbar-responsive
* https://flowbite.com/docs/components/navbar/

**Comment by pwdel** [comment]
What about simplifying this by just creating a, "data collapse toggle" for now?



![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/09b79590-0b5c-47d6-8ada-06c749147ff7)

...

which collapses down into a hamburger menu...?



![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/79299511-b9d8-49fb-91cb-7ffe1d06c0ed)


Which when clicked opens up the menu at the top, overlapping the page?



![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/65d9dd1a-d063-458c-938d-ab87153d263d)

**Comment by markokovac16** [comment]
Sure if the UX is right, if there's too much scrolling to get to all the menu options it's bad UX

**Comment by pwdel** [comment]
For now there will be a maximum of about 6 options, no scrolling. But point taken.

**Comment by pwdel** [comment]
![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/53c75ce1-0f92-4b1e-85a5-fbec0d1e9c44)

**Comment by pwdel** [comment]
![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/9fa2f799-f127-416f-a9c2-d415c820430f)
