### ISSUE TITLE
LOCAL_SETUP: add Docker on WSL 2 link

### ISSUE THREAD

**Issue by astrosnat** [openpredictionmarkets/socialpredict#194]
Users running WSL2 on Windows need to follow a different procedure to install Docker. Link here: [https://docs.docker.com/desktop/wsl/](https://docs.docker.com/desktop/wsl/)

**Comment by pwdel** [comment]
Thanks. Did you test this with Windows? My default has basically been to say, "Windows is not supported." However if you are able to get this going on Windows using the instructions, or if you already have...maybe should I change that documentation?

**Comment by pwdel** [comment]
E.g.... what is documented by docker might be different from the reality of a user trying it out...I don't know. Could be fine. Just would feel more comfortable if someone on our team tried it and certified it first before we endorsed that claim. Does that make sense? Or what do you think?

**Comment by astrosnat** [comment]
Yes, that makes perfect sense. OK, over the weekend I'll assign myself to install Docker on WSL2 and see if I can get SocialPredict up and running from there.

**Comment by astrosnat** [comment]
Update: just tested. You can run SocialPredict on Windows inside WSL2.
