### ISSUE TITLE
Host Frontend as Static Files with Nginx in Prod

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#203]

**Comment by ntoufoudis** [comment]
I was able to resolve this issue by implementing the suggestion made by @donghj2000 in issue #197 

If I add the option
``` commonjsOptions: { transformMixedEsModules: true }```
in the vite.config.mjs file, then Nginx is able to serve the static files without the need for frontend container to run.

If we proceed with my commit on production deployment, I can implement this one as well.

**Comment by j4qfrost** [comment]
Addressed with https://github.com/openpredictionmarkets/socialpredict/pull/341
