### ISSUE TITLE
Update Deployment to Premium Version Which Automatically Replaces config.js and backend with Domain

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#213]
This is just a reminder that the out of the box software includes the following:

```
root@breirfoxforecast-alpha:/home/testdeploy/socialpredict/frontend/src# cd config.js
-bash: cd: config.js: Not a directory
root@breirfoxforecast-alpha:/home/testdeploy/socialpredict/frontend/src# cat config.js
export const DOMAIN_URL = 'https://brierfoxforecast.com';
export const API_URL = 'https://brierfoxforecast.com';
```

This domain should be changable.

Same with the backend CORS domains.

**Comment by pwdel** [comment]
Note, this is already being done in the setup sript:

```
# Function to replace API_URI in frontend/src/config.js
frontend_api_uri() {
	template="$SCRIPT_DIR/frontend/src/config.js.template"
	file="$SCRIPT_DIR/frontend/src/config.js"
	export API_DOMAIN="'http://localhost'"
	envsubst < $template > $file
}
```

So perhaps instead there is a more, "javascript" way of doing this, having javascript pick which config file to use based upon whether it's running in development or prod.

**Comment by ntoufoudis** [comment]
This one is automatically picked from the setup script:
* If it is in development then the domain is set to localhost
* If it is in production then it is set to the domain that was input by the user.

Each change in the config.js means the frontend image needs to be re-built.
