### ISSUE TITLE
Display Total Yes and No Shares

### ISSUE THREAD

**Issue by astrosnat** [openpredictionmarkets/socialpredict#314]
**Describe the bug**

When buying or selling shares only my net shares held are displayed.

**To Reproduce Steps**

    Go to Create
    Click on Create
    Scroll down to Trade
    See error

**Expected behavior**

I should be able to see both my YES and my NO shares

**Screenshots**

![Image](https://github.com/user-attachments/assets/aae747a0-5c99-4a1c-90dc-94202ed8d8c6)
![Image](https://github.com/user-attachments/assets/ba0063ed-5e2b-4ed3-9501-1fa7cbdf4f0e)
![Image](https://github.com/user-attachments/assets/8cc14530-0ff8-4669-8d78-70744efd77ef)
![Image](https://github.com/user-attachments/assets/23c3e80a-4191-4bec-aa59-4fe190f7e7ec)

**Desktop**:

    OS: Ubuntu 22.04 LTS
    Browser: Firefox 130.0
    Version: Pulled from MR 298

**Comment by pwdel** [comment]
Note, by convention a user should only own either YES or NO shares, this is being updated in the math documentation.
