### ISSUE TITLE
Adapt BLK Theme and Dashboard Into React App

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#51]
After having gotten some feedback on potential themes, we had roughly equivalent votes:

<img width="748" alt="image" src="https://github.com/openpredictionmarkets/socialpredict/assets/13304149/77f9133d-3846-4b6a-9a22-ce69cc096919">

Searching around, I found that, "paper dashboard" has a BLK version. People seemed to like the dashboard but also value the black background, so the below themes will likely cover everyone's concerns.

https://manifold.markets/PatrickDelaney/which-set-of-styles-do-you-prefer-f

Theme:

https://www.creative-tim.com/product/blk-design-system-react

Dashboard:

https://www.creative-tim.com/product/black-dashboard-react#

**Comment by shahzad713** [comment]
@pwdel I think it's a great idea. In my opinion, this is the best and user-friendly.
https://www.creative-tim.com/product/black-dashboard-react#
